// Word pairs for the Japanese Word Match game, grouped by JLPT level (N5 = easiest, N1 = hardest).
// Sourced from the elzup/jlpt-word-list dataset (github.com/elzup/jlpt-word-list), itself
// compiled from tanos.co.uk's community JLPT vocabulary lists. Note the JLPT organization
// (Japan Foundation / JEES) has never published an official vocabulary list for any level —
// tanos.co.uk is one of the most widely cited community references, but level placement here
// still reflects that dataset's tagging, not an official source. The 20 words featured per
// level (out of hundreds tagged) are a curated subset picked for gameplay variety and
// unambiguous single-gloss English meanings; readings and level tags are as sourced.
const WORD_LEVELS = [
    {
        level: 1,
        jlpt: 'N5',
        title: 'N5 · Beginner',
        pairs: [
            { jp: '会う', reading: 'あう', en: 'to meet' },
            { jp: '青', reading: 'あお', en: 'blue' },
            { jp: '朝', reading: 'あさ', en: 'morning' },
            { jp: '明日', reading: 'あした', en: 'tomorrow' },
            { jp: '頭', reading: 'あたま', en: 'head' },
            { jp: '新しい', reading: 'あたらしい', en: 'new' },
            { jp: '危ない', reading: 'あぶない', en: 'dangerous' },
            { jp: '雨', reading: 'あめ', en: 'rain' },
            { jp: '歩く', reading: 'あるく', en: 'to walk' },
            { jp: '家', reading: 'いえ', en: 'house' },
            { jp: '忙しい', reading: 'いそがしい', en: 'busy' },
            { jp: '犬', reading: 'いぬ', en: 'dog' },
            { jp: '今', reading: 'いま', en: 'now' },
            { jp: '色', reading: 'いろ', en: 'color' },
            { jp: '歌う', reading: 'うたう', en: 'to sing' },
            { jp: '海', reading: 'うみ', en: 'sea' },
            { jp: '絵', reading: 'え', en: 'painting' },
            { jp: '映画', reading: 'えいが', en: 'movie' },
            { jp: '駅', reading: 'えき', en: 'station' },
            { jp: '大きい', reading: 'おおきい', en: 'big' },
        ],
    },
    {
        level: 2,
        jlpt: 'N4',
        title: 'N4 · Elementary',
        pairs: [
            { jp: '盗む', reading: 'ぬすむ', en: 'to steal' },
            { jp: '生きる', reading: 'いきる', en: 'to live' },
            { jp: '苦い', reading: 'にがい', en: 'bitter' },
            { jp: '意見', reading: 'いけん', en: 'opinion' },
            { jp: '漫画', reading: 'まんが', en: 'comic book' },
            { jp: '必ず', reading: 'かならず', en: 'surely' },
            { jp: '壊す', reading: 'こわす', en: 'to break' },
            { jp: '怒る', reading: 'おこる', en: 'to get angry' },
            { jp: '心配', reading: 'しんぱい', en: 'worry' },
            { jp: '機会', reading: 'きかい', en: 'chance' },
            { jp: '複雑', reading: 'ふくざつ', en: 'complexity' },
            { jp: '大事', reading: 'だいじ', en: 'important' },
            { jp: '台風', reading: 'たいふう', en: 'typhoon' },
            { jp: '過ぎる', reading: 'すぎる', en: 'to exceed' },
            { jp: '必要', reading: 'ひつよう', en: 'necessary' },
            { jp: '地震', reading: 'じしん', en: 'earthquake' },
            { jp: '厳しい', reading: 'きびしい', en: 'strict' },
            { jp: '深い', reading: 'ふかい', en: 'deep' },
            { jp: '悲しい', reading: 'かなしい', en: 'sad' },
            { jp: '小説', reading: 'しょうせつ', en: 'novel' },
        ],
    },
    {
        level: 3,
        jlpt: 'N3',
        title: 'N3 · Intermediate',
        pairs: [
            { jp: '様々', reading: 'さまざま', en: 'various' },
            { jp: '幸せ', reading: 'しあわせ', en: 'happiness' },
            { jp: '事件', reading: 'じけん', en: 'incident' },
            { jp: '事実', reading: 'じじつ', en: 'fact' },
            { jp: '自然', reading: 'しぜん', en: 'nature' },
            { jp: '実験', reading: 'じっけん', en: 'experiment' },
            { jp: '実際', reading: 'じっさい', en: 'actually' },
            { jp: '実力', reading: 'じつりょく', en: 'ability' },
            { jp: '指導', reading: 'しどう', en: 'guidance' },
            { jp: '宗教', reading: 'しゅうきょう', en: 'religion' },
            { jp: '就職', reading: 'しゅうしょく', en: 'employment' },
            { jp: '集中', reading: 'しゅうちゅう', en: 'concentration' },
            { jp: '収入', reading: 'しゅうにゅう', en: 'income' },
            { jp: '重要', reading: 'じゅうよう', en: 'important' },
            { jp: '主張', reading: 'しゅちょう', en: 'claim' },
            { jp: '出版', reading: 'しゅっぱん', en: 'publication' },
            { jp: '主婦', reading: 'しゅふ', en: 'housewife' },
            { jp: '種類', reading: 'しゅるい', en: 'variety' },
            { jp: '順番', reading: 'じゅんばん', en: 'turn (in line)' },
            { jp: '参加', reading: 'さんか', en: 'participation' },
        ],
    },
    {
        level: 4,
        jlpt: 'N2',
        title: 'N2 · Upper Intermediate',
        pairs: [
            { jp: '終了', reading: 'しゅうりょう', en: 'end' },
            { jp: '縮小', reading: 'しゅくしょう', en: 'reduction' },
            { jp: '受験', reading: 'じゅけん', en: 'taking an exam' },
            { jp: '出張', reading: 'しゅっちょう', en: 'business trip' },
            { jp: '順序', reading: 'じゅんじょ', en: 'order' },
            { jp: '純粋', reading: 'じゅんすい', en: 'pure' },
            { jp: '消化', reading: 'しょうか', en: 'digestion' },
            { jp: '商業', reading: 'しょうぎょう', en: 'commerce' },
            { jp: '上級', reading: 'じょうきゅう', en: 'advanced level' },
            { jp: '賞金', reading: 'しょうきん', en: 'prize money' },
            { jp: '商店', reading: 'しょうてん', en: 'shop' },
            { jp: '焦点', reading: 'しょうてん', en: 'focus' },
            { jp: '正面', reading: 'しょうめん', en: 'front' },
            { jp: '職場', reading: 'しょくば', en: 'workplace' },
            { jp: '資料', reading: 'しりょう', en: 'materials' },
            { jp: '新幹線', reading: 'しんかんせん', en: 'bullet train' },
            { jp: '申請', reading: 'しんせい', en: 'application' },
            { jp: '診断', reading: 'しんだん', en: 'diagnosis' },
            { jp: '森林', reading: 'しんりん', en: 'forest' },
            { jp: '水平線', reading: 'すいへいせん', en: 'horizon' },
        ],
    },
    {
        level: 5,
        jlpt: 'N1',
        title: 'N1 · Advanced',
        pairs: [
            { jp: '原則', reading: 'げんそく', en: 'principle' },
            { jp: '見地', reading: 'けんち', en: 'viewpoint' },
            { jp: '厳密', reading: 'げんみつ', en: 'rigorous' },
            { jp: '賢明', reading: 'けんめい', en: 'wise' },
            { jp: '権力', reading: 'けんりょく', en: 'power' },
            { jp: '語彙', reading: 'ごい', en: 'vocabulary' },
            { jp: '好意', reading: 'こうい', en: 'goodwill' },
            { jp: '抗議', reading: 'こうぎ', en: 'protest' },
            { jp: '交渉', reading: 'こうしょう', en: 'negotiation' },
            { jp: '向上', reading: 'こうじょう', en: 'improvement' },
            { jp: '購入', reading: 'こうにゅう', en: 'purchase' },
            { jp: '効率', reading: 'こうりつ', en: 'efficiency' },
            { jp: '告白', reading: 'こくはく', en: 'confession' },
            { jp: '国防', reading: 'こくぼう', en: 'national defense' },
            { jp: '心得', reading: 'こころえ', en: 'knowledge' },
            { jp: '誤差', reading: 'ごさ', en: 'error' },
            { jp: '孤独', reading: 'こどく', en: 'loneliness' },
            { jp: '誇張', reading: 'こちょう', en: 'exaggeration' },
            { jp: '個性', reading: 'こせい', en: 'individuality' },
            { jp: '固定', reading: 'こてい', en: 'fixed' },
        ],
    },
];
