// Word pairs for the Japanese Word Match game, grouped by JLPT level (N5 = easiest, N1 = hardest).
// Each level has 5 word sets of 20 pairs (40 tiles); a random set is chosen each time a level
// is played, so replaying gives fresh vocabulary.
//
// Sourced from the elzup/jlpt-word-list dataset (github.com/elzup/jlpt-word-list), itself
// compiled from tanos.co.uk's community JLPT vocabulary lists. Note the JLPT organization
// (Japan Foundation / JEES) has never published an official vocabulary list for any level —
// tanos.co.uk is one of the most widely cited community references, but level placement here
// still reflects that dataset's tagging, not an official source. The 100 words featured per
// level (out of hundreds tagged) are a curated subset picked for gameplay variety and
// unambiguous single-gloss English meanings; readings and level tags are as sourced.
const WORD_LEVELS = [
    {
        level: 1,
        jlpt: 'N5',
        title: 'N5 · Beginner',
        sets: [
            [
                { jp: "会う", reading: "あう", en: "to meet" },
                { jp: "青", reading: "あお", en: "blue" },
                { jp: "朝", reading: "あさ", en: "morning" },
                { jp: "明日", reading: "あした", en: "tomorrow" },
                { jp: "頭", reading: "あたま", en: "head" },
                { jp: "新しい", reading: "あたらしい", en: "new" },
                { jp: "危ない", reading: "あぶない", en: "dangerous" },
                { jp: "雨", reading: "あめ", en: "rain" },
                { jp: "歩く", reading: "あるく", en: "to walk" },
                { jp: "家", reading: "いえ", en: "house" },
                { jp: "忙しい", reading: "いそがしい", en: "busy" },
                { jp: "犬", reading: "いぬ", en: "dog" },
                { jp: "今", reading: "いま", en: "now" },
                { jp: "色", reading: "いろ", en: "color" },
                { jp: "歌う", reading: "うたう", en: "to sing" },
                { jp: "海", reading: "うみ", en: "sea" },
                { jp: "絵", reading: "え", en: "painting" },
                { jp: "映画", reading: "えいが", en: "movie" },
                { jp: "駅", reading: "えき", en: "station" },
                { jp: "大きい", reading: "おおきい", en: "big" },
            ],
            [
                { jp: "外国", reading: "がいこく", en: "foreign country" },
                { jp: "会社", reading: "かいしゃ", en: "company" },
                { jp: "階段", reading: "かいだん", en: "stairs" },
                { jp: "買い物", reading: "かいもの", en: "shopping" },
                { jp: "買う", reading: "かう", en: "to buy" },
                { jp: "帰る", reading: "かえる", en: "to go back" },
                { jp: "顔", reading: "かお", en: "face" },
                { jp: "鍵", reading: "かぎ", en: "key" },
                { jp: "書く", reading: "かく", en: "to write" },
                { jp: "学生", reading: "がくせい", en: "student" },
                { jp: "傘", reading: "かさ", en: "umbrella" },
                { jp: "貸す", reading: "かす", en: "to lend" },
                { jp: "風", reading: "かぜ", en: "wind" },
                { jp: "家族", reading: "かぞく", en: "family" },
                { jp: "学校", reading: "がっこう", en: "school" },
                { jp: "家庭", reading: "かてい", en: "home" },
                { jp: "かばん", reading: "かばん", en: "bag" },
                { jp: "紙", reading: "かみ", en: "paper" },
                { jp: "カメラ", reading: "カメラ", en: "camera" },
                { jp: "体", reading: "からだ", en: "body" },
            ],
            [
                { jp: "借りる", reading: "かりる", en: "to borrow" },
                { jp: "軽い", reading: "かるい", en: "light" },
                { jp: "川", reading: "かわ", en: "river" },
                { jp: "可愛い", reading: "かわいい", en: "cute" },
                { jp: "漢字", reading: "かんじ", en: "kanji" },
                { jp: "木", reading: "き", en: "tree" },
                { jp: "黄色", reading: "きいろ", en: "yellow" },
                { jp: "聞く", reading: "きく", en: "to hear" },
                { jp: "北", reading: "きた", en: "north" },
                { jp: "ギター", reading: "ギター", en: "guitar" },
                { jp: "汚い", reading: "きたない", en: "dirty" },
                { jp: "喫茶店", reading: "きっさてん", en: "cafe" },
                { jp: "切符", reading: "きっぷ", en: "ticket" },
                { jp: "昨日", reading: "きのう", en: "yesterday" },
                { jp: "九", reading: "く", en: "nine" },
                { jp: "牛肉", reading: "ぎゅうにく", en: "beef" },
                { jp: "牛乳", reading: "ぎゅうにゅう", en: "milk" },
                { jp: "今日", reading: "きょう", en: "today" },
                { jp: "教室", reading: "きょうしつ", en: "classroom" },
                { jp: "兄弟", reading: "きょうだい", en: "siblings" },
            ],
            [
                { jp: "去年", reading: "きょねん", en: "last year" },
                { jp: "嫌い", reading: "きらい", en: "dislike" },
                { jp: "切る", reading: "きる", en: "to cut" },
                { jp: "綺麗", reading: "きれい", en: "pretty" },
                { jp: "銀行", reading: "ぎんこう", en: "bank" },
                { jp: "薬", reading: "くすり", en: "medicine" },
                { jp: "果物", reading: "くだもの", en: "fruit" },
                { jp: "靴", reading: "くつ", en: "shoes" },
                { jp: "靴下", reading: "くつした", en: "socks" },
                { jp: "国", reading: "くに", en: "country" },
                { jp: "曇り", reading: "くもり", en: "cloudy" },
                { jp: "暗い", reading: "くらい", en: "dark" },
                { jp: "クラス", reading: "クラス", en: "class" },
                { jp: "来る", reading: "くる", en: "to come" },
                { jp: "車", reading: "くるま", en: "car" },
                { jp: "黒", reading: "くろ", en: "black" },
                { jp: "警官", reading: "けいかん", en: "police officer" },
                { jp: "今朝", reading: "けさ", en: "this morning" },
                { jp: "五", reading: "ご", en: "five" },
                { jp: "元気", reading: "げんき", en: "healthy" },
            ],
            [
                { jp: "公園", reading: "こうえん", en: "park" },
                { jp: "交差点", reading: "こうさてん", en: "intersection" },
                { jp: "紅茶", reading: "こうちゃ", en: "black tea" },
                { jp: "交番", reading: "こうばん", en: "police box" },
                { jp: "声", reading: "こえ", en: "voice" },
                { jp: "コーヒー", reading: "コーヒー", en: "coffee" },
                { jp: "午後", reading: "ごご", en: "afternoon" },
                { jp: "答える", reading: "こたえる", en: "to answer" },
                { jp: "今年", reading: "ことし", en: "this year" },
                { jp: "言葉", reading: "ことば", en: "language" },
                { jp: "子供", reading: "こども", en: "child" },
                { jp: "御飯", reading: "ごはん", en: "rice (cooked)" },
                { jp: "困る", reading: "こまる", en: "to be bothered" },
                { jp: "今月", reading: "こんげつ", en: "this month" },
                { jp: "今週", reading: "こんしゅう", en: "this week" },
                { jp: "今晩", reading: "こんばん", en: "tonight" },
                { jp: "財布", reading: "さいふ", en: "wallet" },
                { jp: "魚", reading: "さかな", en: "fish" },
                { jp: "先", reading: "さき", en: "future" },
                { jp: "咲く", reading: "さく", en: "to bloom" },
            ],
        ],
    },
    {
        level: 2,
        jlpt: 'N4',
        title: 'N4 · Elementary',
        sets: [
            [
                { jp: "盗む", reading: "ぬすむ", en: "to steal" },
                { jp: "生きる", reading: "いきる", en: "to live" },
                { jp: "苦い", reading: "にがい", en: "bitter" },
                { jp: "意見", reading: "いけん", en: "opinion" },
                { jp: "漫画", reading: "まんが", en: "comic book" },
                { jp: "必ず", reading: "かならず", en: "surely" },
                { jp: "壊す", reading: "こわす", en: "to break" },
                { jp: "怒る", reading: "おこる", en: "to get angry" },
                { jp: "心配", reading: "しんぱい", en: "worry" },
                { jp: "機会", reading: "きかい", en: "chance" },
                { jp: "複雑", reading: "ふくざつ", en: "complexity" },
                { jp: "大事", reading: "だいじ", en: "important" },
                { jp: "台風", reading: "たいふう", en: "typhoon" },
                { jp: "過ぎる", reading: "すぎる", en: "to exceed" },
                { jp: "必要", reading: "ひつよう", en: "necessary" },
                { jp: "地震", reading: "じしん", en: "earthquake" },
                { jp: "厳しい", reading: "きびしい", en: "strict" },
                { jp: "深い", reading: "ふかい", en: "deep" },
                { jp: "悲しい", reading: "かなしい", en: "sad" },
                { jp: "小説", reading: "しょうせつ", en: "novel" },
            ],
            [
                { jp: "運動", reading: "うんどう", en: "exercise" },
                { jp: "表", reading: "おもて", en: "surface" },
                { jp: "大学生", reading: "だいがくせい", en: "college student" },
                { jp: "運転手", reading: "うんてんしゅ", en: "driver" },
                { jp: "別", reading: "べつ", en: "distinction" },
                { jp: "非常に", reading: "ひじょうに", en: "extremely" },
                { jp: "気", reading: "き", en: "spirit" },
                { jp: "比べる", reading: "くらべる", en: "to compare" },
                { jp: "郊外", reading: "こうがい", en: "suburb" },
                { jp: "正月", reading: "しょうがつ", en: "New Year" },
                { jp: "規則", reading: "きそく", en: "rule" },
                { jp: "発音", reading: "はつおん", en: "pronunciation" },
                { jp: "焼く", reading: "やく", en: "to bake" },
                { jp: "失礼", reading: "しつれい", en: "discourtesy" },
                { jp: "今度", reading: "こんど", en: "this time" },
                { jp: "彼", reading: "かれ", en: "he" },
                { jp: "布団", reading: "ふとん", en: "futon" },
                { jp: "贈り物", reading: "おくりもの", en: "gift" },
                { jp: "泥棒", reading: "どろぼう", en: "thief" },
                { jp: "注意", reading: "ちゅうい", en: "caution" },
            ],
            [
                { jp: "通る", reading: "とおる", en: "to pass by" },
                { jp: "葉", reading: "は", en: "leaf" },
                { jp: "課長", reading: "かちょう", en: "section manager" },
                { jp: "すると", reading: "すると", en: "then" },
                { jp: "止める", reading: "とめる", en: "to end" },
                { jp: "ガラス", reading: "ガラス", en: "glass" },
                { jp: "エスカレーター", reading: "エスカレーター", en: "escalator" },
                { jp: "人口", reading: "じんこう", en: "population" },
                { jp: "月", reading: "つき", en: "moon" },
                { jp: "絹", reading: "きぬ", en: "silk" },
                { jp: "壊れる", reading: "こわれる", en: "to be broken" },
                { jp: "揺れる", reading: "ゆれる", en: "to shake" },
                { jp: "祈る", reading: "いのる", en: "to pray" },
                { jp: "盛ん", reading: "さかん", en: "prosperous" },
                { jp: "アルバイト", reading: "アルバイト", en: "part-time job" },
                { jp: "起こす", reading: "おこす", en: "to wake someone" },
                { jp: "噛む", reading: "かむ", en: "to bite" },
                { jp: "赤ちゃん", reading: "あかちゃん", en: "baby" },
                { jp: "浅い", reading: "あさい", en: "shallow" },
                { jp: "親", reading: "おや", en: "parent" },
            ],
            [
                { jp: "それに", reading: "それに", en: "moreover" },
                { jp: "西洋", reading: "せいよう", en: "the West" },
                { jp: "思う", reading: "おもう", en: "to think" },
                { jp: "時代", reading: "じだい", en: "era" },
                { jp: "申し上げる", reading: "もうしあげる", en: "to say (humble)" },
                { jp: "出席", reading: "しゅっせき", en: "attendance" },
                { jp: "迎える", reading: "むかえる", en: "to welcome" },
                { jp: "触る", reading: "さわる", en: "to touch" },
                { jp: "社長", reading: "しゃちょう", en: "company president" },
                { jp: "動物園", reading: "どうぶつえん", en: "zoo" },
                { jp: "捕まえる", reading: "つかまえる", en: "to catch" },
                { jp: "寄る", reading: "よる", en: "to stop by" },
                { jp: "決まる", reading: "きまる", en: "to be decided" },
                { jp: "開く", reading: "ひらく", en: "to open" },
                { jp: "逃げる", reading: "にげる", en: "to escape" },
                { jp: "だから", reading: "だから", en: "so" },
                { jp: "残念", reading: "ざんねん", en: "regret" },
                { jp: "丁寧", reading: "ていねい", en: "polite" },
                { jp: "地理", reading: "ちり", en: "geography" },
                { jp: "さっき", reading: "さっき", en: "a little while ago" },
            ],
            [
                { jp: "怖い", reading: "こわい", en: "scary" },
                { jp: "包む", reading: "つつむ", en: "to wrap" },
                { jp: "なるべく", reading: "なるべく", en: "if possible" },
                { jp: "無理", reading: "むり", en: "unreasonable" },
                { jp: "サンドイッチ", reading: "サンドイッチ", en: "sandwich" },
                { jp: "会議室", reading: "かいぎしつ", en: "conference room" },
                { jp: "品物", reading: "しなもの", en: "goods" },
                { jp: "人形", reading: "にんぎょう", en: "doll" },
                { jp: "利用", reading: "りよう", en: "use" },
                { jp: "飾る", reading: "かざる", en: "to decorate" },
                { jp: "恥ずかしい", reading: "はずかしい", en: "ashamed" },
                { jp: "頑張る", reading: "がんばる", en: "to try one's best" },
                { jp: "投げる", reading: "なげる", en: "to pitch" },
                { jp: "力", reading: "ちから", en: "strength" },
                { jp: "気分", reading: "きぶん", en: "feeling" },
                { jp: "間違える", reading: "まちがえる", en: "to make a mistake" },
                { jp: "星", reading: "ほし", en: "star" },
                { jp: "場合", reading: "ばあい", en: "case" },
                { jp: "やっと", reading: "やっと", en: "at last" },
                { jp: "足りる", reading: "たりる", en: "to be sufficient" },
            ],
        ],
    },
    {
        level: 3,
        jlpt: 'N3',
        title: 'N3 · Intermediate',
        sets: [
            [
                { jp: "様々", reading: "さまざま", en: "various" },
                { jp: "幸せ", reading: "しあわせ", en: "happiness" },
                { jp: "事件", reading: "じけん", en: "incident" },
                { jp: "事実", reading: "じじつ", en: "fact" },
                { jp: "自然", reading: "しぜん", en: "nature" },
                { jp: "実験", reading: "じっけん", en: "experiment" },
                { jp: "実際", reading: "じっさい", en: "actually" },
                { jp: "実力", reading: "じつりょく", en: "ability" },
                { jp: "指導", reading: "しどう", en: "guidance" },
                { jp: "宗教", reading: "しゅうきょう", en: "religion" },
                { jp: "就職", reading: "しゅうしょく", en: "employment" },
                { jp: "集中", reading: "しゅうちゅう", en: "concentration" },
                { jp: "収入", reading: "しゅうにゅう", en: "income" },
                { jp: "重要", reading: "じゅうよう", en: "important" },
                { jp: "主張", reading: "しゅちょう", en: "claim" },
                { jp: "出版", reading: "しゅっぱん", en: "publication" },
                { jp: "主婦", reading: "しゅふ", en: "housewife" },
                { jp: "種類", reading: "しゅるい", en: "variety" },
                { jp: "順番", reading: "じゅんばん", en: "turn (in line)" },
                { jp: "参加", reading: "さんか", en: "participation" },
            ],
            [
                { jp: "作法", reading: "さほう", en: "manners" },
                { jp: "左右", reading: "さゆう", en: "left and right" },
                { jp: "皿", reading: "さら", en: "plate" },
                { jp: "参考", reading: "さんこう", en: "reference" },
                { jp: "賛成", reading: "さんせい", en: "approval" },
                { jp: "酸素", reading: "さんそ", en: "oxygen" },
                { jp: "詩", reading: "し", en: "poem" },
                { jp: "四季", reading: "しき", en: "four seasons" },
                { jp: "資源", reading: "しげん", en: "resources" },
                { jp: "自殺", reading: "じさつ", en: "suicide" },
                { jp: "自身", reading: "じしん", en: "oneself" },
                { jp: "沈む", reading: "しずむ", en: "to sink" },
                { jp: "舌", reading: "した", en: "tongue" },
                { jp: "親しい", reading: "したしい", en: "intimate" },
                { jp: "質", reading: "しつ", en: "quality" },
                { jp: "失業", reading: "しつぎょう", en: "unemployment" },
                { jp: "実現", reading: "じつげん", en: "implementation" },
                { jp: "実は", reading: "じつは", en: "in fact" },
                { jp: "失望", reading: "しつぼう", en: "disappointment" },
                { jp: "支店", reading: "してん", en: "branch office" },
            ],
            [
                { jp: "自動", reading: "じどう", en: "automatic" },
                { jp: "児童", reading: "じどう", en: "children" },
                { jp: "支配", reading: "しはい", en: "rule" },
                { jp: "芝居", reading: "しばい", en: "drama" },
                { jp: "支払う", reading: "しはらう", en: "to pay" },
                { jp: "死亡", reading: "しぼう", en: "death" },
                { jp: "資本", reading: "しほん", en: "funds" },
                { jp: "姉妹", reading: "しまい", en: "sisters" },
                { jp: "自慢", reading: "じまん", en: "pride" },
                { jp: "地味", reading: "じみ", en: "plain" },
                { jp: "示す", reading: "しめす", en: "to show" },
                { jp: "占める", reading: "しめる", en: "to take up" },
                { jp: "借金", reading: "しゃっきん", en: "debt" },
                { jp: "週", reading: "しゅう", en: "week" },
                { jp: "州", reading: "しゅう", en: "state" },
                { jp: "銃", reading: "じゅう", en: "gun" },
                { jp: "周囲", reading: "しゅうい", en: "surroundings" },
                { jp: "収穫", reading: "しゅうかく", en: "harvest" },
                { jp: "重視", reading: "じゅうし", en: "importance" },
                { jp: "修正", reading: "しゅうせい", en: "amendment" },
            ],
            [
                { jp: "集団", reading: "しゅうだん", en: "group" },
                { jp: "住民", reading: "じゅうみん", en: "inhabitants" },
                { jp: "修理", reading: "しゅうり", en: "repairing" },
                { jp: "主義", reading: "しゅぎ", en: "doctrine" },
                { jp: "宿泊", reading: "しゅくはく", en: "lodging" },
                { jp: "手術", reading: "しゅじゅつ", en: "surgical operation" },
                { jp: "首相", reading: "しゅしょう", en: "Prime Minister" },
                { jp: "手段", reading: "しゅだん", en: "means" },
                { jp: "出身", reading: "しゅっしん", en: "hometown" },
                { jp: "首都", reading: "しゅと", en: "capital city" },
                { jp: "主要", reading: "しゅよう", en: "main" },
                { jp: "需要", reading: "じゅよう", en: "demand" },
                { jp: "瞬間", reading: "しゅんかん", en: "moment" },
                { jp: "順調", reading: "じゅんちょう", en: "going well" },
                { jp: "賞", reading: "しょう", en: "prize" },
                { jp: "障害", reading: "しょうがい", en: "obstacle" },
                { jp: "奨学金", reading: "しょうがくきん", en: "scholarship" },
                { jp: "乗客", reading: "じょうきゃく", en: "passenger" },
                { jp: "状況", reading: "じょうきょう", en: "situation" },
                { jp: "条件", reading: "じょうけん", en: "condition" },
            ],
            [
                { jp: "正午", reading: "しょうご", en: "noon" },
                { jp: "正直", reading: "しょうじき", en: "honesty" },
                { jp: "常識", reading: "じょうしき", en: "common sense" },
                { jp: "少女", reading: "しょうじょ", en: "young girl" },
                { jp: "症状", reading: "しょうじょう", en: "symptoms" },
                { jp: "状態", reading: "じょうたい", en: "state" },
                { jp: "上達", reading: "じょうたつ", en: "improvement" },
                { jp: "冗談", reading: "じょうだん", en: "a joke" },
                { jp: "衝突", reading: "しょうとつ", en: "collision" },
                { jp: "商売", reading: "しょうばい", en: "business" },
                { jp: "消費", reading: "しょうひ", en: "consumption" },
                { jp: "商品", reading: "しょうひん", en: "commodity" },
                { jp: "情報", reading: "じょうほう", en: "information" },
                { jp: "証明", reading: "しょうめい", en: "proof" },
                { jp: "職業", reading: "しょくぎょう", en: "occupation" },
                { jp: "植物", reading: "しょくぶつ", en: "plant" },
                { jp: "食欲", reading: "しょくよく", en: "appetite" },
                { jp: "女優", reading: "じょゆう", en: "actress" },
                { jp: "処理", reading: "しょり", en: "processing" },
                { jp: "書類", reading: "しょるい", en: "documents" },
            ],
        ],
    },
    {
        level: 4,
        jlpt: 'N2',
        title: 'N2 · Upper Intermediate',
        sets: [
            [
                { jp: "終了", reading: "しゅうりょう", en: "end" },
                { jp: "縮小", reading: "しゅくしょう", en: "reduction" },
                { jp: "受験", reading: "じゅけん", en: "taking an exam" },
                { jp: "出張", reading: "しゅっちょう", en: "business trip" },
                { jp: "順序", reading: "じゅんじょ", en: "order" },
                { jp: "純粋", reading: "じゅんすい", en: "pure" },
                { jp: "消化", reading: "しょうか", en: "digestion" },
                { jp: "商業", reading: "しょうぎょう", en: "commerce" },
                { jp: "上級", reading: "じょうきゅう", en: "advanced level" },
                { jp: "賞金", reading: "しょうきん", en: "prize money" },
                { jp: "商店", reading: "しょうてん", en: "shop" },
                { jp: "焦点", reading: "しょうてん", en: "focus" },
                { jp: "正面", reading: "しょうめん", en: "front" },
                { jp: "職場", reading: "しょくば", en: "workplace" },
                { jp: "資料", reading: "しりょう", en: "materials" },
                { jp: "新幹線", reading: "しんかんせん", en: "bullet train" },
                { jp: "申請", reading: "しんせい", en: "application" },
                { jp: "診断", reading: "しんだん", en: "diagnosis" },
                { jp: "森林", reading: "しんりん", en: "forest" },
                { jp: "水平線", reading: "すいへいせん", en: "horizon" },
            ],
            [
                { jp: "就任", reading: "しゅうにん", en: "inauguration" },
                { jp: "周辺", reading: "しゅうへん", en: "vicinity" },
                { jp: "重役", reading: "じゅうやく", en: "director" },
                { jp: "重量", reading: "じゅうりょう", en: "weight" },
                { jp: "重力", reading: "じゅうりょく", en: "gravity" },
                { jp: "熟語", reading: "じゅくご", en: "idiom" },
                { jp: "祝日", reading: "しゅくじつ", en: "national holiday" },
                { jp: "主語", reading: "しゅご", en: "subject (grammar)" },
                { jp: "寿命", reading: "じゅみょう", en: "life span" },
                { jp: "主役", reading: "しゅやく", en: "leading role" },
                { jp: "受話器", reading: "じゅわき", en: "telephone receiver" },
                { jp: "循環", reading: "じゅんかん", en: "circulation" },
                { jp: "巡査", reading: "じゅんさ", en: "policeman" },
                { jp: "順々", reading: "じゅんじゅん", en: "in order" },
                { jp: "純情", reading: "じゅんじょう", en: "pure heart" },
                { jp: "将棋", reading: "しょうぎ", en: "Japanese chess" },
                { jp: "蒸気", reading: "じょうき", en: "steam" },
                { jp: "定規", reading: "じょうぎ", en: "ruler" },
                { jp: "消極的", reading: "しょうきょくてき", en: "passive" },
                { jp: "上下", reading: "じょうげ", en: "up and down" },
            ],
            [
                { jp: "障子", reading: "しょうじ", en: "sliding door" },
                { jp: "商社", reading: "しょうしゃ", en: "trading company" },
                { jp: "乗車", reading: "じょうしゃ", en: "boarding a train" },
                { jp: "上旬", reading: "じょうじゅん", en: "early part of month" },
                { jp: "生ずる", reading: "しょうずる", en: "to cause" },
                { jp: "小数", reading: "しょうすう", en: "fraction" },
                { jp: "消毒", reading: "しょうどく", en: "disinfection" },
                { jp: "勝敗", reading: "しょうはい", en: "win or loss" },
                { jp: "蒸発", reading: "じょうはつ", en: "evaporation" },
                { jp: "上品", reading: "じょうひん", en: "refined" },
                { jp: "消防署", reading: "しょうぼうしょ", en: "fire station" },
                { jp: "正味", reading: "しょうみ", en: "net weight" },
                { jp: "消耗", reading: "しょうもう", en: "exhaustion" },
                { jp: "初級", reading: "しょきゅう", en: "beginner level" },
                { jp: "助教授", reading: "じょきょうじゅ", en: "assistant professor" },
                { jp: "食塩", reading: "しょくえん", en: "table salt" },
                { jp: "職人", reading: "しょくにん", en: "artisan" },
                { jp: "書籍", reading: "しょせき", en: "book" },
                { jp: "食器", reading: "しょっき", en: "tableware" },
                { jp: "書店", reading: "しょてん", en: "bookshop" },
            ],
            [
                { jp: "書道", reading: "しょどう", en: "calligraphy" },
                { jp: "白髪", reading: "しらが", en: "gray hair" },
                { jp: "素人", reading: "しろうと", en: "amateur" },
                { jp: "芯", reading: "しん", en: "core" },
                { jp: "真空", reading: "しんくう", en: "vacuum" },
                { jp: "人事", reading: "じんじ", en: "personnel" },
                { jp: "心身", reading: "しんしん", en: "mind and body" },
                { jp: "人造", reading: "じんぞう", en: "man-made" },
                { jp: "寝台", reading: "しんだい", en: "berth" },
                { jp: "侵入", reading: "しんにゅう", en: "invasion" },
                { jp: "人文科学", reading: "じんぶんかがく", en: "humanities" },
                { jp: "人命", reading: "じんめい", en: "human life" },
                { jp: "深夜", reading: "しんや", en: "late at night" },
                { jp: "針路", reading: "しんろ", en: "course" },
                { jp: "神話", reading: "しんわ", en: "myth" },
                { jp: "水産", reading: "すいさん", en: "marine products" },
                { jp: "炊事", reading: "すいじ", en: "cooking" },
                { jp: "水蒸気", reading: "すいじょうき", en: "water vapor" },
                { jp: "水素", reading: "すいそ", en: "hydrogen" },
                { jp: "垂直", reading: "すいちょく", en: "vertical" },
            ],
            [
                { jp: "推定", reading: "すいてい", en: "presumption" },
                { jp: "水筒", reading: "すいとう", en: "water bottle" },
                { jp: "随筆", reading: "ずいひつ", en: "essay" },
                { jp: "水分", reading: "すいぶん", en: "moisture" },
                { jp: "水平", reading: "すいへい", en: "horizontal" },
                { jp: "水面", reading: "すいめん", en: "water surface" },
                { jp: "頭脳", reading: "ずのう", en: "brain" },
                { jp: "隙間", reading: "すきま", en: "gap" },
                { jp: "鈴", reading: "すず", en: "bell" },
                { jp: "涼む", reading: "すずむ", en: "to cool oneself" },
                { jp: "素直", reading: "すなお", en: "obedient" },
                { jp: "寸法", reading: "すんぽう", en: "measurement" },
                { jp: "税関", reading: "ぜいかん", en: "customs" },
                { jp: "製作", reading: "せいさく", en: "production" },
                { jp: "清書", reading: "せいしょ", en: "clean copy" },
                { jp: "整数", reading: "せいすう", en: "integer" },
                { jp: "清掃", reading: "せいそう", en: "cleaning" },
                { jp: "生存", reading: "せいぞん", en: "existence" },
                { jp: "性能", reading: "せいのう", en: "performance" },
                { jp: "整備", reading: "せいび", en: "maintenance" },
            ],
        ],
    },
    {
        level: 5,
        jlpt: 'N1',
        title: 'N1 · Advanced',
        sets: [
            [
                { jp: "原則", reading: "げんそく", en: "principle" },
                { jp: "見地", reading: "けんち", en: "viewpoint" },
                { jp: "厳密", reading: "げんみつ", en: "rigorous" },
                { jp: "賢明", reading: "けんめい", en: "wise" },
                { jp: "権力", reading: "けんりょく", en: "power" },
                { jp: "語彙", reading: "ごい", en: "vocabulary" },
                { jp: "好意", reading: "こうい", en: "goodwill" },
                { jp: "抗議", reading: "こうぎ", en: "protest" },
                { jp: "交渉", reading: "こうしょう", en: "negotiation" },
                { jp: "向上", reading: "こうじょう", en: "improvement" },
                { jp: "購入", reading: "こうにゅう", en: "purchase" },
                { jp: "効率", reading: "こうりつ", en: "efficiency" },
                { jp: "告白", reading: "こくはく", en: "confession" },
                { jp: "国防", reading: "こくぼう", en: "national defense" },
                { jp: "心得", reading: "こころえ", en: "knowledge" },
                { jp: "誤差", reading: "ごさ", en: "error" },
                { jp: "孤独", reading: "こどく", en: "loneliness" },
                { jp: "誇張", reading: "こちょう", en: "exaggeration" },
                { jp: "個性", reading: "こせい", en: "individuality" },
                { jp: "固定", reading: "こてい", en: "fixed" },
            ],
            [
                { jp: "限定", reading: "げんてい", en: "limit" },
                { jp: "原油", reading: "げんゆ", en: "crude oil" },
                { jp: "言論", reading: "げんろん", en: "discussion" },
                { jp: "行為", reading: "こうい", en: "act" },
                { jp: "合意", reading: "ごうい", en: "agreement" },
                { jp: "工学", reading: "こうがく", en: "engineering" },
                { jp: "皇居", reading: "こうきょ", en: "Imperial Palace" },
                { jp: "鉱業", reading: "こうぎょう", en: "mining industry" },
                { jp: "高原", reading: "こうげん", en: "highland" },
                { jp: "考古学", reading: "こうこがく", en: "archaeology" },
                { jp: "工作", reading: "こうさく", en: "handicraft" },
                { jp: "鉱山", reading: "こうざん", en: "mine" },
                { jp: "講習", reading: "こうしゅう", en: "short course" },
                { jp: "口述", reading: "こうじゅつ", en: "oral statement" },
                { jp: "高尚", reading: "こうしょう", en: "refined" },
                { jp: "行進", reading: "こうしん", en: "march" },
                { jp: "香辛料", reading: "こうしんりょう", en: "spices" },
                { jp: "洪水", reading: "こうずい", en: "flood" },
                { jp: "構想", reading: "こうそう", en: "concept" },
                { jp: "後退", reading: "こうたい", en: "retreat" },
            ],
            [
                { jp: "光沢", reading: "こうたく", en: "luster" },
                { jp: "公団", reading: "こうだん", en: "public corporation" },
                { jp: "好調", reading: "こうちょう", en: "favorable" },
                { jp: "口頭", reading: "こうとう", en: "oral" },
                { jp: "購読", reading: "こうどく", en: "subscription" },
                { jp: "公認", reading: "こうにん", en: "official recognition" },
                { jp: "光熱費", reading: "こうねつひ", en: "utility costs" },
                { jp: "好評", reading: "こうひょう", en: "popularity" },
                { jp: "交付", reading: "こうふ", en: "issuance" },
                { jp: "公募", reading: "こうぼ", en: "public appeal" },
                { jp: "巧妙", reading: "こうみょう", en: "ingenious" },
                { jp: "公用", reading: "こうよう", en: "official use" },
                { jp: "小売", reading: "こうり", en: "retail" },
                { jp: "公立", reading: "こうりつ", en: "public institution" },
                { jp: "護衛", reading: "ごえい", en: "escort" },
                { jp: "小柄", reading: "こがら", en: "small build" },
                { jp: "小切手", reading: "こぎって", en: "cheque" },
                { jp: "国産", reading: "こくさん", en: "domestic product" },
                { jp: "国定", reading: "こくてい", en: "state-sponsored" },
                { jp: "国有", reading: "こくゆう", en: "national ownership" },
            ],
            [
                { jp: "極楽", reading: "ごくらく", en: "paradise" },
                { jp: "国連", reading: "こくれん", en: "United Nations" },
                { jp: "語源", reading: "ごげん", en: "etymology" },
                { jp: "心地", reading: "ここち", en: "feeling" },
                { jp: "心掛け", reading: "こころがけ", en: "readiness" },
                { jp: "志", reading: "こころざし", en: "ambition" },
                { jp: "心強い", reading: "こころづよい", en: "reassuring" },
                { jp: "心細い", reading: "こころぼそい", en: "helpless" },
                { jp: "試み", reading: "こころみ", en: "attempt" },
                { jp: "快い", reading: "こころよい", en: "pleasant" },
                { jp: "孤児", reading: "こじ", en: "orphan" },
                { jp: "戸籍", reading: "こせき", en: "family register" },
                { jp: "古代", reading: "こだい", en: "ancient times" },
                { jp: "滑稽", reading: "こっけい", en: "funny" },
                { jp: "国交", reading: "こっこう", en: "diplomatic relations" },
                { jp: "骨董品", reading: "こっとうひん", en: "antique" },
                { jp: "事柄", reading: "ことがら", en: "matter" },
                { jp: "個別", reading: "こべつ", en: "individual case" },
                { jp: "言付け", reading: "ことづけ", en: "message" },
                { jp: "殊に", reading: "ことに", en: "especially" },
            ],
            [
                { jp: "好ましい", reading: "このましい", en: "desirable" },
                { jp: "碁盤", reading: "ごばん", en: "Go board" },
                { jp: "ごまかす", reading: "ごまかす", en: "to deceive" },
                { jp: "細やか", reading: "こまやか", en: "delicate" },
                { jp: "込める", reading: "こめる", en: "to include" },
                { jp: "固有", reading: "こゆう", en: "characteristic" },
                { jp: "暦", reading: "こよみ", en: "calendar" },
                { jp: "凝らす", reading: "こらす", en: "to concentrate" },
                { jp: "懲りる", reading: "こりる", en: "to learn a lesson" },
                { jp: "根気", reading: "こんき", en: "patience" },
                { jp: "根拠", reading: "こんきょ", en: "basis" },
                { jp: "混血", reading: "こんけつ", en: "mixed race" },
                { jp: "昆虫", reading: "こんちゅう", en: "insect" },
                { jp: "根底", reading: "こんてい", en: "root" },
                { jp: "混同", reading: "こんどう", en: "confusion" },
                { jp: "根本", reading: "こんぽん", en: "fundamental" },
                { jp: "財", reading: "ざい", en: "wealth" },
                { jp: "再会", reading: "さいかい", en: "reunion" },
                { jp: "災害", reading: "さいがい", en: "disaster" },
                { jp: "細菌", reading: "さいきん", en: "bacteria" },
            ],
        ],
    },
];
